# https://www.graphile.org/postgraphile/deploying-gcp/

beta_settings:
  cloud_sql_instances: eco-azimuth-275417:us-east1:laurier-rugby=tcp:5432

# [START runtime]
runtime: nodejs
env: flex
threadsafe: yes

automatic_scaling:
  min_instances: 0
  max_concurrent_requests: 50
resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10

# [END runtime]

handlers:
  - url: /(.*)
    static_files: ./\1
    upload: ./(.*)

#  settings to keep gcloud from uploading files not required for deployment
skip_files:
  - ^node_modules$
  - ^README\..*
  - ^package-lock.json
  - \.gitignore
  - \.es*
  - ^\.git$
  - ^errors\.log